<?php

namespace Database\Seeders;

use App\Models\Telephone;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TelephoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['name' => "R. MOH. KUN TAUCHID", 'position' => "Manager Production Sei Pakning", 'department' => "MAN PROD SPK", 'address' => "VIP 3", 'employee_number' => "0", 'office_phone' => "4200", 'home_phone' => "4334"],
            ['name' => "PUSKODAL KTR INDUK", 'position' => "Puskodal", 'department' => "MAN PROD SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4701", 'home_phone' => "0"],
            ['name' => "SURYADI", 'position' => "Secretary Man Prod Spk", 'department' => "MAN PROD SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4204", 'home_phone' => "0"],
            ['name' => "ISWANDI", 'position' => "Off II Fac & Quality", 'department' => "PRODUCTION SPK", 'address' => "JL. Anggrek R.01", 'employee_number' => "743023", 'office_phone' => "4214", 'home_phone' => "4679"],
            ['name' => "YANTI PICAULI", 'position' => "Adm Distribution BBM", 'department' => "DISTR BBM SPK", 'address' => "Gedung Production Spk", 'employee_number' => "0", 'office_phone' => "4305", 'home_phone' => "4685"],
            ['name' => "SITI NASIBAH", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Kantor Maintenance", 'employee_number' => "0", 'office_phone' => "4325", 'home_phone' => "0"],
            ['name' => "RICO SATRIA", 'position' => "Supervisor Preventive Maintenance", 'department' => "MAINTENANCE SPK", 'address' => "Jl. Sedap Malam E.49", 'employee_number' => "746380", 'office_phone' => "4368", 'home_phone' => "4615"],
            ['name' => "RAZIMAN", 'position' => "Jr. Engineer NRE & Civil", 'department' => "MAINTENANCE SPK", 'address' => "JL. Flamboyan E. 22", 'employee_number' => "748259", 'office_phone' => "4327", 'home_phone' => "4596"],
            ['name' => "AMDANI NASUTION", 'position' => "Section Head Production", 'department' => "PRODUCTION SPK", 'address' => "Jl. Wijaya Kusuma B. 01", 'employee_number' => "0", 'office_phone' => "4210", 'home_phone' => "4410"],
            ['name' => "AGUSTINA", 'position' => "Adm Production Spk", 'department' => "PRODUCTION SPK", 'address' => "Gedung Production Spk", 'employee_number' => "0", 'office_phone' => "4310", 'home_phone' => "0"],
            ['name' => "JUNAIDI", 'position' => "SR SPV ITY", 'department' => "PRODUCTION SPK", 'address' => "Jl. Anggrek BB. 03", 'employee_number' => "728299", 'office_phone' => "4212", 'home_phone' => "4622"],
            ['name' => "AMAN SOLEH RITONGA", 'position' => "SHFT SPV LAB", 'department' => "PRODUCTION SPK", 'address' => "C. 07", 'employee_number' => "747228", 'office_phone' => "4219", 'home_phone' => "4539"],
            ['name' => "RIYANTO", 'position' => "PAELMAN I CDU", 'department' => "PRODUCTION SPK", 'address' => "Jl. Sedap Malam E. 50", 'employee_number' => "745229", 'office_phone' => "4163", 'home_phone' => "4568"],
            ['name' => "MARLAN ALBETHRUS MANURUNG", 'position' => "JR TESTER II LAB", 'department' => "PRODUCTION SPK", 'address' => "JL. Mangga D. 33", 'employee_number' => "751072", 'office_phone' => "4304", 'home_phone' => "4517"],
            ['name' => "ZULFIKAR SYAH", 'position' => "JR OPRT II IPAL & SEPRATOR", 'department' => "PRODUCTION SPK", 'address' => "JL. Rambutan D. 44", 'employee_number' => "752212", 'office_phone' => "4255", 'home_phone' => "4503"],
            ['name' => "MUHAMMAD HARYADI", 'position' => "JR TESTER II LAB", 'department' => "PRODUCTION SPK", 'address' => "JL. Kenanga E. 12", 'employee_number' => "753101", 'office_phone' => "4304", 'home_phone' => "0"],
            ['name' => "MUHAMAD HENDRIK", 'position' => "JR OPR II JETTY", 'department' => "PRODUCTION SPK", 'address' => "JL. Wijaya Kusuma E. 10", 'employee_number' => "753085", 'office_phone' => "4304", 'home_phone' => "4556"],
            ['name' => "FAZRI AULIA RAMADHAN", 'position' => "JR TESTER II LAB", 'department' => "PRODUCTION SPK", 'address' => "JL. Kenanga E. 17", 'employee_number' => "751237", 'office_phone' => "4304", 'home_phone' => "4657"],
            ['name' => "SUBRATA", 'position' => "PANELMAN III CDU", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E. 26", 'employee_number' => "747219", 'office_phone' => "4315", 'home_phone' => "4544"],
            ['name' => "JAPRINAL", 'position' => "Technician I NRE & Civil", 'department' => "MAINTENANCE SPK", 'address' => "JL. Wijaya Kusuma E.01", 'employee_number' => "746092", 'office_phone' => "4347", 'home_phone' => "4566"],
            ['name' => "BOBBY DERMAWAN", 'position' => "JR OPR II JETTY", 'department' => "PRODUCTION SPK", 'address' => "JL. Wijaya Kusuma E. 51", 'employee_number' => "753119", 'office_phone' => "4304", 'home_phone' => "4655"],
            ['name' => "JANUARDI", 'position' => "OPR I HEATER & TOWER", 'department' => "PRODUCTION SPK", 'address' => "JL. Kenanga E.11", 'employee_number' => "751078", 'office_phone' => "4315", 'home_phone' => "4526"],
            ['name' => "FACHREZA ARDIAN", 'position' => "JR OPR II TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "751230", 'office_phone' => "4302", 'home_phone' => "0"],
            ['name' => "DARWINSYAH", 'position' => "OPR I HEATER & TOWER", 'department' => "PRODUCTION SPK", 'address' => "JL. Wijaya Kusuma E. 06", 'employee_number' => "746111", 'office_phone' => "4315", 'home_phone' => "4635"],
            ['name' => "M. IQBAL", 'position' => "JR OPR II PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E.33", 'employee_number' => "753093", 'office_phone' => "4315", 'home_phone' => "4528"],
            ['name' => "ADHE SYAPUTRA", 'position' => "PANELMAN III CDU", 'department' => "PRODUCTION SPK", 'address' => "JL. Mangga D.40", 'employee_number' => "747221", 'office_phone' => "4315", 'home_phone' => "4478"],
            ['name' => "M. ZULYADI", 'position' => "SHIF SPV PUMP H & JETTY", 'department' => "PRODUCTION SPK", 'address' => "JL. Cemara A 01 A", 'employee_number' => "746382", 'office_phone' => "4319", 'home_phone' => "4567"],
            ['name' => "IBNU SABILILLAH", 'position' => "JR OPR II HEATER & TOWER", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "753102", 'office_phone' => "4315", 'home_phone' => "4631"],
            ['name' => "RIAN FADILAH MUHAMMAD", 'position' => "JR OPR II PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "Jl. Sedap Malam E. 48", 'employee_number' => "753080", 'office_phone' => "4315", 'home_phone' => "0"],
            ['name' => "MUHARDARISON", 'position' => "SR SPV LABORATORY", 'department' => "PRODUCTION SPK", 'address' => "JL. Tanjung C.07", 'employee_number' => "728403", 'office_phone' => "4215", 'home_phone' => "4651"],
            ['name' => "BAIDARUS", 'position' => "Shift Supervisor CDU", 'department' => "PRODUCTION SPK", 'address' => "JL. Tanjung C. 10", 'employee_number' => "728282", 'office_phone' => "4313", 'home_phone' => "4653"],
            ['name' => "ANTONY SIHOMBING", 'position' => "Supervisor Power & Distribution", 'department' => "PRODUCTION SPK", 'address' => "JL. Teratai R.08", 'employee_number' => "728363", 'office_phone' => "4344", 'home_phone' => "4623"],
            ['name' => "HERU PRATAMA", 'position' => "PANELMAN I METERING", 'department' => "PRODUCTION SPK", 'address' => "Jl. Sedap Malam D.03", 'employee_number' => "747223", 'office_phone' => "4344", 'home_phone' => "4614"],
            ['name' => "ABEDNEGO SINAGA", 'position' => "JR OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "Jl. Sedap Malam D.14", 'employee_number' => "751079", 'office_phone' => "4344", 'home_phone' => "4527"],
            ['name' => "FARIED THIOMALIKI", 'position' => "JR OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "751234", 'office_phone' => "4344", 'home_phone' => "4452"],
            ['name' => "HENRY ANANDAR LT", 'position' => "SHIFT SPV LAB", 'department' => "PRODUCTION SPK", 'address' => "JL. Melati D.19", 'employee_number' => "747043", 'office_phone' => "4344", 'home_phone' => "4637"],
            ['name' => "PURWADI", 'position' => "SR OPR II WTP/WDCF/WIS", 'department' => "PRODUCTION SPK", 'address' => "JL. Mangga D.38", 'employee_number' => "748257", 'office_phone' => "4344", 'home_phone' => "4524"],
            ['name' => "ABDUL AZIZ", 'position' => "JR OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "JL. Rambutan E. 32", 'employee_number' => "753109", 'office_phone' => "4344", 'home_phone' => "4582"],
            ['name' => "MUHAMMAD FAHMI EDWIN", 'position' => "JR OPR II PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E.", 'employee_number' => "753088", 'office_phone' => "4344", 'home_phone' => "4456"],
            ['name' => "SURYA DARMAWAN", 'position' => "SR OPR II WTP/WDCF/WIS", 'department' => "PRODUCTION SPK", 'address' => "Jl. Sedap Malam D.21", 'employee_number' => "747045", 'office_phone' => "4344", 'home_phone' => "4639"],
            ['name' => "MEIRYAN SOFFANO", 'position' => "Panelman III Boiler & Aux", 'department' => "PRODUCTION SPK", 'address' => "JL. Kenanga E.18", 'employee_number' => "743267", 'office_phone' => "4311", 'home_phone' => "4588"],
            ['name' => "ADRIANSYAH", 'position' => "Panelman III Boiler & Aux", 'department' => "PRODUCTION SPK", 'address' => "C. 09", 'employee_number' => "743178", 'office_phone' => "4311", 'home_phone' => "4418"],
            ['name' => "ANDRI SUGIANA", 'position' => "JR OPR II WTP/WDCF/WIS", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E. 27", 'employee_number' => "753071", 'office_phone' => "4193", 'home_phone' => "4453"],
            ['name' => "HERRIYANTO ABDI SIREGAR", 'position' => "PANELMAN I CDU", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E.42", 'employee_number' => "745226", 'office_phone' => "4193", 'home_phone' => "4688"],
            ['name' => "ADRIAN GUSFERI", 'position' => "PANELMAN I BOILER & AUX", 'department' => "PRODUCTION SPK", 'address' => "Jl. Sedap Malam D.23", 'employee_number' => "745234", 'office_phone' => "4193", 'home_phone' => "4529"],
            ['name' => "ABDUL GOFUR NASUTION", 'position' => "JR OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "JL. Mangga D. 35", 'employee_number' => "751076", 'office_phone' => "0", 'home_phone' => "4516"],
            ['name' => "ARYS MANDA ALPARISI", 'position' => "JR OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "751227", 'office_phone' => "4193", 'home_phone' => "4455"],
            ['name' => "SAMPE SUNARDI TAMPUL GANA HUTABARAT", 'position' => "JR OPR II PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E. 25", 'employee_number' => "752205", 'office_phone' => "4196", 'home_phone' => "4531"],
            ['name' => "YANDI YULIA JAYA", 'position' => "PANELMAN II BOILER/AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Rambutan D. 37", 'employee_number' => "747232", 'office_phone' => "4193", 'home_phone' => "4454"],
            ['name' => "RONNY PASULIMA", 'position' => "OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "JL. Kenanga E.16", 'employee_number' => "746135", 'office_phone' => "4193", 'home_phone' => "4616"],
            ['name' => "RISSALDI ZAIN", 'position' => "OPR II DIST & POWER", 'department' => "PRODUCTION SPK", 'address' => "JL. Flamboyan E. 35", 'employee_number' => "746130", 'office_phone' => "4344", 'home_phone' => "4565"],
            ['name' => "BENNY FERDIAN", 'position' => "PANELMAN I METERING", 'department' => "PRODUCTION SPK", 'address' => "JL. Rambutan D. 42", 'employee_number' => "746130", 'office_phone' => "4216", 'home_phone' => "4677"],
            ['name' => "DANIEL", 'position' => "OPR I TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Sedap Malam D. 11", 'employee_number' => "746103", 'office_phone' => "4216", 'home_phone' => "4636"],
            ['name' => "ANDI BUCHARI", 'position' => "OPR I TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Melati D.20", 'employee_number' => "746122", 'office_phone' => "4216", 'home_phone' => "4518"],
            ['name' => "AHMAD FADLI", 'position' => "OPR I TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Kenanga E.20", 'employee_number' => "747225", 'office_phone' => "4216", 'home_phone' => "4554"],
            ['name' => "BUDI TRIYANTO", 'position' => "OPR II TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Melati D.16", 'employee_number' => "750286", 'office_phone' => "4216", 'home_phone' => "4513"],
            ['name' => "FADLY AZMI", 'position' => "Jr Operator I Tanki Pump & Aux", 'department' => "PRODUCTION SPK", 'address' => "JL. Durian D.25", 'employee_number' => "751077", 'office_phone' => "4216", 'home_phone' => "4519"],
            ['name' => "ADE WIBOWO", 'position' => "ANALISY I DISTRIBUTION BBM", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "747222", 'office_phone' => "4214", 'home_phone' => "4663"],
            ['name' => "SUKRI RAHMADHANI", 'position' => "PANELMAN I METERING", 'department' => "PRODUCTION SPK", 'address' => "JL. Mangga D.41", 'employee_number' => "747218", 'office_phone' => "4216", 'home_phone' => "4677"],
            ['name' => "INSANULKAMIL", 'position' => "JR OPR II TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "751246", 'office_phone' => "4216", 'home_phone' => "0"],
            ['name' => "R. RAPAT MCR", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Gedung MCR", 'employee_number' => "0", 'office_phone' => "4209", 'home_phone' => "0"],
            ['name' => "SYAMSUL", 'position' => "Adm Laboratory", 'department' => "PRODUCTION SPK", 'address' => "Gedung Laboratory", 'employee_number' => "0", 'office_phone' => "4219", 'home_phone' => "0"],
            ['name' => "SEMFARI", 'position' => "Adm Utilities", 'department' => "PRODUCTION SPK", 'address' => "Gedung Production Spk", 'employee_number' => "0", 'office_phone' => "4194", 'home_phone' => "0"],
            ['name' => "BOILER", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Area Boiler", 'employee_number' => "0", 'office_phone' => "4306", 'home_phone' => "0"],
            ['name' => "R. SEDIMENTASI", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Gedung WTP", 'employee_number' => "0", 'office_phone' => "4195", 'home_phone' => "0"],
            ['name' => "SUPPORTING", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "0", 'office_phone' => "4317", 'home_phone' => "0"],
            ['name' => "AREA SAMPLE", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "AREA SAMPLE", 'employee_number' => "0", 'office_phone' => "4324", 'home_phone' => "0"],
            ['name' => "SEPERATOR", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "JL. C AREA KILANG", 'employee_number' => "0", 'office_phone' => "4229", 'home_phone' => "0"],
            ['name' => "FILLING SHEED BBM", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "JL. B AREA KILANG", 'employee_number' => "0", 'office_phone' => "4218", 'home_phone' => "0"],
            ['name' => "AREA TANKI 05", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "AREA TANKI 05", 'employee_number' => "0", 'office_phone' => "4303", 'home_phone' => "0"],
            ['name' => "AREA TANKI 12", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "AREA TANKI 12", 'employee_number' => "0", 'office_phone' => "4301", 'home_phone' => "0"],
            ['name' => "JETTY I", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "AREA MARINE", 'employee_number' => "0", 'office_phone' => "4302", 'home_phone' => "0"],
            ['name' => "JETTY I", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "AREA MARINE", 'employee_number' => "0", 'office_phone' => "4307", 'home_phone' => "0"],
            ['name' => "JETTY II", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Jetty II", 'employee_number' => "0", 'office_phone' => "4309", 'home_phone' => "0"],
            ['name' => "FAISAL", 'position' => "Adm IT&Y", 'department' => "PRODUCTION SPK", 'address' => "Gedung Production Spk", 'employee_number' => "0", 'office_phone' => "4318", 'home_phone' => "0"],
            ['name' => "ALFIAN NUR", 'position' => "Section Head Maintenance", 'department' => "MAINTENANCE SPK", 'address' => "Jl. Nusa Indah B. 04", 'employee_number' => "713783", 'office_phone' => "4240", 'home_phone' => "4440"],
            ['name' => "R. RAPAT MAINTENANCE", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4155", 'home_phone' => "0"],
            ['name' => "RAHMANIAR", 'position' => "Adm Maintenance", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4245", 'home_phone' => "0"],
            ['name' => "PRIHARTONO", 'position' => "Engineer I Rotating Equipment", 'department' => "MAINTENANCE SPK", 'address' => "Jl. Melati C. 05", 'employee_number' => "747229", 'office_phone' => "4350", 'home_phone' => "4448"],
            ['name' => "STEFANUS BUDI SANTOSA", 'position' => "Engineer I Electrical & Instrument", 'department' => "MAINTENANCE SPK", 'address' => "JL. Melati D.22", 'employee_number' => "747039", 'office_phone' => "4257", 'home_phone' => "4641"],
            ['name' => "EDY SUSANTO", 'position' => "Jr Techncian II Construction & Welding", 'department' => "MAINTENANCE SPK", 'address' => "JL. Rambutan D.", 'employee_number' => "752211", 'office_phone' => "4347", 'home_phone' => "0"],
            ['name' => "MUHABIBIE NUR", 'position' => "Jr Analyst II T/A & O/H", 'department' => "MAINTENANCE SPK", 'address' => "JL. MANGGA D. 34", 'employee_number' => "748254", 'office_phone' => "4247", 'home_phone' => "4558"],
            ['name' => "ERI ISTIADI AMBARITA", 'position' => "OFFICER I HSE COMPLICE", 'department' => "PRODUCTION SPK", 'address' => "JL. Mangga D.26", 'employee_number' => "747639", 'office_phone' => "4396", 'home_phone' => "4546"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Adm Technician Mechanical & Civil", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Mech & Civil", 'employee_number' => "0", 'office_phone' => "4187", 'home_phone' => "0"],
            ['name' => "RANDI", 'position' => "Supervisor Electrical & Instrument", 'department' => "MAINTENANCE SPK", 'address' => "JL. Mangga D.32", 'employee_number' => "748258", 'office_phone' => "4346", 'home_phone' => "4523"],
            ['name' => "RANDI", 'position' => "Supervisor Electrical & Instrument", 'department' => "MAINTENANCE SPK", 'address' => "JL. Mangga D.32", 'employee_number' => "748258", 'office_phone' => "4346", 'home_phone' => "4523"],
            ['name' => "AFRIZAL", 'position' => "Jr. Technician II Instrument", 'department' => "MAINTENANCE SPK", 'address' => "JL. Wijaya Kusuma E.09", 'employee_number' => "752691", 'office_phone' => "4346", 'home_phone' => "4545"],
            ['name' => "JUNAIDI PARLAUNGAN GULTOM", 'position' => "Jr. Technician II RE", 'department' => "MAINTENANCE SPK", 'address' => "Jl. Sedap Malam E. 46", 'employee_number' => "752688", 'office_phone' => "4187", 'home_phone' => "4522"],
            ['name' => "CHAIRIL", 'position' => "Supervisor Planning Routine", 'department' => "MAINTENANCE SPK", 'address' => "JL. Melati C. 04", 'employee_number' => "747633", 'office_phone' => "4237", 'home_phone' => "4449"],
            ['name' => "JUNAIDI TANJUNG", 'position' => "Jr Technician II Workshop", 'department' => "-", 'address' => "Jl. Flamboyan E.34", 'employee_number' => "747389", 'office_phone' => "4166", 'home_phone' => "4447"],
            ['name' => "ZYULFAN MS", 'position' => "Technician I Office & Housing Facility", 'department' => "MAINTENANCE SPK", 'address' => "-", 'employee_number' => "752707", 'office_phone' => "4342", 'home_phone' => "0"],
            ['name' => "ARIYANTO", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4242", 'home_phone' => "0"],
            ['name' => "ARIYANTO", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4242", 'home_phone' => "0"],
            ['name' => "ARIYANTO", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4242", 'home_phone' => "0"],
            ['name' => "ARIYANTO", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4242", 'home_phone' => "0"],
            ['name' => "CREW MECH UTILITIES", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Mech", 'employee_number' => "0", 'office_phone' => "4166", 'home_phone' => "0"],
            ['name' => "CREW MECH CIVIL", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Civil", 'employee_number' => "0", 'office_phone' => "4342", 'home_phone' => "0"],
            ['name' => "CREW ALAT BERAT", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Workshop Maintenance", 'employee_number' => "0", 'office_phone' => "4351", 'home_phone' => "0"],
            ['name' => "TRAFO JETTY", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Area Jetty", 'employee_number' => "0", 'office_phone' => "4249", 'home_phone' => "0"],
            ['name' => "ADM PUBLIC FACILITY", 'position' => "-", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Public Facility", 'employee_number' => "0", 'office_phone' => "4244", 'home_phone' => "0"],
            ['name' => "LINDA", 'position' => "Adm Planning", 'department' => "MAINTENANCE SPK", 'address' => "Gedung Maintenance", 'employee_number' => "0", 'office_phone' => "4251", 'home_phone' => "0"],
            ['name' => "HARIS", 'position' => "Section Head HSSE Sei Pakning", 'department' => "-", 'address' => "Jl. Nusa Indah B. 03", 'employee_number' => "0", 'office_phone' => "4333", 'home_phone' => "4444"],
            ['name' => "EZI", 'position' => "Adm HSSE", 'department' => "HSSE SPK", 'address' => "Gedung HSE", 'employee_number' => "0", 'office_phone' => "4321", 'home_phone' => "0"],
            ['name' => "ANDRI RIADI S", 'position' => "743031", 'department' => "PRODUCTION SPK", 'address' => "JL. Cemara A 02 A", 'employee_number' => "743031", 'office_phone' => "4304", 'home_phone' => "4613"],
            ['name' => "M. SYAFII", 'position' => "Sr Fireman I RU II - S Pakning", 'department' => "HSSE SPK", 'address' => "JL. Flamboyan E. 29", 'employee_number' => "747643", 'office_phone' => "4322", 'home_phone' => "4424"],
            ['name' => "RIKI ADYA PUTRA", 'position' => "Sr Fireman I RU II - S Pakning", 'department' => "HSSE SPK", 'address' => "JL. Sedap Malam E.43", 'employee_number' => "747649", 'office_phone' => "4322", 'home_phone' => "4425"],
            ['name' => "RIO MARTADINATA", 'position' => "Sr Fireman I RU II - S Pakning", 'department' => "HSSE SPK", 'address' => "JL. Wijaya Kusuma E.07", 'employee_number' => "747651", 'office_phone' => "4322", 'home_phone' => "4423"],
            ['name' => "M.SYAHLAN DWI PUTRA .S", 'position' => "-", 'department' => "HSSE SPK", 'address' => "JL. Kenanga E.13", 'employee_number' => "753116", 'office_phone' => "4322", 'home_phone' => "4411"],
            ['name' => "FIRE STATION", 'position' => "-", 'department' => "HSE SPK", 'address' => "Gedung HSE", 'employee_number' => "0", 'office_phone' => "4322", 'home_phone' => "0"],
            ['name' => "CLASS ROOM", 'position' => "-", 'department' => "HSE SPK", 'address' => "Gedung HSE", 'employee_number' => "0", 'office_phone' => "4102", 'home_phone' => "0"],
            ['name' => "FIRE PUMP HOUSE", 'position' => "-", 'department' => "HSSE SPK", 'address' => "Area Jetty I", 'employee_number' => "0", 'office_phone' => "4223", 'home_phone' => "0"],
            ['name' => "EMERGENCY FIRE ONLY", 'position' => "-", 'department' => "HSE SPK", 'address' => "Gedung HSE", 'employee_number' => "0", 'office_phone' => "999", 'home_phone' => "0"],
            ['name' => "DEDI KURNIADI", 'position' => "Section Head Procurement", 'department' => "PROCUREMENT SPK", 'address' => "Jl. Melati C.01", 'employee_number' => "0", 'office_phone' => "4270", 'home_phone' => "4470"],
            ['name' => "MURNI", 'position' => "Adm Procurement", 'department' => "PROCUREMENT SPK", 'address' => "-", 'employee_number' => "0", 'office_phone' => "4281", 'home_phone' => "0"],
            ['name' => "R. RAPAT PROCUREMENT", 'position' => "-", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4284", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "-", 'department' => "-", 'address' => "-", 'employee_number' => "0", 'office_phone' => "4380", 'home_phone' => "0"],
            ['name' => "GUNTUR", 'position' => "-", 'department' => "PROCUREMENT SPK", 'address' => "JL. Kenanga E.19", 'employee_number' => "0", 'office_phone' => "4380", 'home_phone' => "4583"],
            ['name' => "ERNA IMELDA", 'position' => "Sr Supervisor GA", 'department' => "GA SPK", 'address' => "Jl. Flamboyan E.37", 'employee_number' => "719397", 'office_phone' => "4286", 'home_phone' => "4601"],
            ['name' => "SAFRUDDIN", 'position' => "-", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4285", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak ", 'position' => "Jr Assistant Inv & Transportation", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4382", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Jr Assistant Receiving", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4202", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Adm Angkutan", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Poll Angkutan", 'employee_number' => "0", 'office_phone' => "4383", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Crew Poll Angkutan", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Poll Angkutan", 'employee_number' => "0", 'office_phone' => "4388", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Pengisian BBM", 'department' => "PROCUREMENT SPK", 'address' => "gedung Pengisian BBM", 'employee_number' => "0", 'office_phone' => "4385", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Stationary", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4129", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Stationary", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4129", 'home_phone' => "0"],
            ['name' => "RUDI", 'position' => "Fotocopy", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4228", 'home_phone' => "0"],
            ['name' => "SULAIMAN", 'position' => "Fotocopy", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4283", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "RTK / RTP", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Procurement", 'employee_number' => "0", 'office_phone' => "4239", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak ", 'position' => "Gudang Yard", 'department' => "PROCUREMENT SPK", 'address' => "Gedung Gudang Procurement", 'employee_number' => "0", 'office_phone' => "4384", 'home_phone' => "0"],
            ['name' => "KARYA NOVEN", 'position' => "SHIFT SPV CDU", 'department' => "PRODUCTION SPK", 'address' => "JL. Melati C.02", 'employee_number' => "728111", 'office_phone' => "4319", 'home_phone' => "4652"],
            ['name' => "M. ARIF EDWARD", 'position' => "LOAD MASTER II SPK", 'department' => "PRODUCTION SPK", 'address' => "JL. Anggrek R.05", 'employee_number' => "743161", 'office_phone' => "4314", 'home_phone' => "4498"],
            ['name' => "ADE GUSNADI", 'position' => "JR OPR II JETTY", 'department' => "PRODUCTION SPK", 'address' => "JL. Rambutan D. 48", 'employee_number' => "753076", 'office_phone' => "4302", 'home_phone' => "4457"],
            ['name' => "HARI MARDIANTO", 'position' => "JR OPR II TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "JL. Rambutan D.45", 'employee_number' => "752198", 'office_phone' => "4302", 'home_phone' => "4556"],
            ['name' => "SAAD", 'position' => "JR OPR II TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "Jl. Flamboyan E.37", 'employee_number' => "752690", 'office_phone' => "4302", 'home_phone' => "4617"],
            ['name' => "SUYADI", 'position' => "JR OPR II TANK PUMP & AUX", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "752701", 'office_phone' => "4302", 'home_phone' => "0"],
            ['name' => "IDA", 'position' => "Adm Jr Assistant Administration", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4224", 'home_phone' => "0"],
            ['name' => "YANTI", 'position' => "Adm Jr Assistant Administration", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4233", 'home_phone' => "0"],
            ['name' => "AMRIL NORMAN", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4235", 'home_phone' => "0"],
            ['name' => "RAHMAD HIDAYAT", 'position' => "Jr Assistant Management Support", 'department' => "GA SPK", 'address' => "JL. Cemara A01B", 'employee_number' => "746139", 'office_phone' => "4295", 'home_phone' => "4569"],
            ['name' => "NAZRAH", 'position' => "Adm CSR", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4296", 'home_phone' => "0"],
            ['name' => "KHAIRUL FADILLAH", 'position' => "Dokumentasi CSR", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4297", 'home_phone' => "0"],
            ['name' => "MULYADI", 'position' => "Adm Security", 'department' => "HSE SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4293", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Jr Assistant Phy & NonPhy &Permit Sec.", 'department' => "GA SPK", 'address' => "Posko Kilang", 'employee_number' => "0", 'office_phone' => "4291", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Jr Assistant Phy & NonPhy &Permit Sec.", 'department' => "GA SPK", 'address' => "Posko Kilang", 'employee_number' => "0", 'office_phone' => "4291", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Jr Assistant Phy & NonPhy &Permit Sec.", 'department' => "GA SPK", 'address' => "Posko Kilang", 'employee_number' => "0", 'office_phone' => "4291", 'home_phone' => "0"],
            ['name' => "M. NASIR", 'position' => "Group Head Physical Security", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4292", 'home_phone' => "0"],
            ['name' => "FADLI", 'position' => "Sandi", 'department' => "GA SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4299", 'home_phone' => "0"],
            ['name' => "ARI YAHYA", 'position' => "Pendamping Head Refinery Sector", 'department' => "GA SPK", 'address' => "JL. Mawar FC.18", 'employee_number' => "0", 'office_phone' => "4143", 'home_phone' => "4496"],
            ['name' => "FIRDAUS", 'position' => "Pendamping Head Refinery Sector", 'department' => "GA SPK", 'address' => "JL. Teratai TH.04", 'employee_number' => "0", 'office_phone' => "4143", 'home_phone' => "4495"],
            ['name' => "M.B. HIDAYAT", 'position' => "Pendamping Head Refinery Sector", 'department' => "GA SPK", 'address' => "JL. Mangga CO.06", 'employee_number' => "0", 'office_phone' => "4140", 'home_phone' => "4493"],
            ['name' => "POSKO KILANG", 'position' => "-", 'department' => "GA SPK", 'address' => "Posko Kilang", 'employee_number' => "0", 'office_phone' => "4140", 'home_phone' => "0"],
            ['name' => "POS I", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Marine", 'employee_number' => "0", 'office_phone' => "4141", 'home_phone' => "0"],
            ['name' => "POS II", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Bambu Kuning", 'employee_number' => "0", 'office_phone' => "4142", 'home_phone' => "0"],
            ['name' => "POS III", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Pintu Masuk Perumahan", 'employee_number' => "0", 'office_phone' => "4143", 'home_phone' => "0"],
            ['name' => "POS IV", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Airport", 'employee_number' => "0", 'office_phone' => "4144", 'home_phone' => "0"],
            ['name' => "POS V", 'position' => "-", 'department' => "GA SPK", 'address' => "JL. C Area Kilang", 'employee_number' => "0", 'office_phone' => "4145", 'home_phone' => "0"],
            ['name' => "POS VI", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Kantor Induk", 'employee_number' => "0", 'office_phone' => "4146", 'home_phone' => "0"],
            ['name' => "POS VII", 'position' => "-", 'department' => "0", 'address' => "RDP B.01", 'employee_number' => "0", 'office_phone' => "4147", 'home_phone' => "0"],
            ['name' => "POS BANTU JL. B", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Marine", 'employee_number' => "0", 'office_phone' => "4151", 'home_phone' => "0"],
            ['name' => "POS PKD", 'position' => "-", 'department' => "GA SPK", 'address' => "Area BULOPA", 'employee_number' => "0", 'office_phone' => "4152", 'home_phone' => "0"],
            ['name' => "POS YS", 'position' => "-", 'department' => "GA SPK", 'address' => "JL. Ketapang", 'employee_number' => "0", 'office_phone' => "4153", 'home_phone' => "0"],
            ['name' => "LEONARDO BENJAMIN", 'position' => "Marine Sungai Pakning", 'department' => "-", 'address' => "JL. Tanjung R.12", 'employee_number' => "0", 'office_phone' => "4271", 'home_phone' => "4471"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "-", 'department' => "MARINE REG I SPK", 'address' => "Gedung Marine", 'employee_number' => "0", 'office_phone' => "4277", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Shift Shipping Agency", 'department' => "MARINE REG I SPK", 'address' => "Gedung Marine", 'employee_number' => "0", 'office_phone' => "4275", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Shift Shipping Agency", 'department' => "MARINE REG I SPK", 'address' => "Gedung Marine", 'employee_number' => "0", 'office_phone' => "4274", 'home_phone' => "0"],
            ['name' => "SITI AISAH", 'position' => "Adm Operation Marine", 'department' => "MARINE REG I SPK", 'address' => "Gedung Marine", 'employee_number' => "0", 'office_phone' => "4273", 'home_phone' => "0"],
            ['name' => "CINDY", 'position' => "Adm Port Facility", 'department' => "MARINE REG I SPK", 'address' => "Gedung Marine", 'employee_number' => "0", 'office_phone' => "4364", 'home_phone' => "0"],
            ['name' => "HOUSE BOAT", 'position' => "-", 'department' => "MARINE REG I SPK", 'address' => "Area Marine", 'employee_number' => "0", 'office_phone' => "4376", 'home_phone' => "0"],
            ['name' => "GUDANG PTM / LLP", 'position' => "-", 'department' => "MARINE REG I SPK", 'address' => "Area Marine", 'employee_number' => "0", 'office_phone' => "4378", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak ", 'position' => "-", 'department' => "FINANCE SPK", 'address' => "KANTOR INDUK", 'employee_number' => "0", 'office_phone' => "4260", 'home_phone' => "0"],
            ['name' => "JALENA", 'position' => "Adm Finance Spk", 'department' => "FINANCE SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4362", 'home_phone' => "0"],
            ['name' => "ZARNETTY", 'position' => "-", 'department' => "FINANCE SPK", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4265", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Shipping On Call", 'department' => "FINANCE SPK", 'address' => "Area Marine", 'employee_number' => "0", 'office_phone' => "4366", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "0", 'department' => "-", 'address' => "-", 'employee_number' => "0", 'office_phone' => "4112", 'home_phone' => "0"],
            ['name' => "HERDIANSYAH H", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4110", 'home_phone' => "0"],
            ['name' => "DARUSSAMIN", 'position' => "Adm BP & RB Spk", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4125", 'home_phone' => "0"],
            ['name' => "EMERGENCY", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4111", 'home_phone' => "0"],
            ['name' => "EMERGENCY", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4111", 'home_phone' => "0"],
            ['name' => "EMERGENCY", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4122", 'home_phone' => "0"],
            ['name' => "PENDAFTARAN KLINIK", 'position' => "Pendaftaran", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4123", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Poli Umum", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4205", 'home_phone' => "0"],
            ['name' => "JUNIANTO", 'position' => "Sr. Supervisor Planning", 'department' => "MAINTENANCE SPK", 'address' => "Jl. Teratai R.02", 'employee_number' => "728388", 'office_phone' => "4345", 'home_phone' => "4675"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "UJI Kes", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4124", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Labor", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4126", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Apotik", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4115", 'home_phone' => "0"],
            ['name' => "R. Radiologi", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4128", 'home_phone' => "0"],
            ['name' => "MESS PUTRA", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "JL. Mangga CO.03", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4436"],
            ['name' => "MESS PUTRI", 'position' => "-", 'department' => "BP & RB", 'address' => "JL. Mangga CO.02", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4564"],
            ['name' => "MESS PUTRI", 'position' => "-", 'department' => "BP & RB", 'address' => "JL. Mangga CO.02", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4564"],
            ['name' => "R. PERAWATAN Bougenvile", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4208", 'home_phone' => "0"],
            ['name' => "R. PERAWATAN Edelwies", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4113", 'home_phone' => "0"],
            ['name' => "R. PERAWATAN Anggrek", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4120", 'home_phone' => "0"],
            ['name' => "R. PERAWATAN Flamboyan", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4117", 'home_phone' => "0"],
            ['name' => "R. PERAWATAN Dahlia", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4118", 'home_phone' => "0"],
            ['name' => "R. PERAWATAN Mawar", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4114", 'home_phone' => "0"],
            ['name' => "R. ISOLASI", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4116", 'home_phone' => "0"],
            ['name' => "DAPUR / FITNES", 'position' => "-", 'department' => "KLINIK PRATAMA", 'address' => "Gedung Klinik Pratama", 'employee_number' => "0", 'office_phone' => "4206", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "-", 'department' => "I.T SPK", 'address' => "-", 'employee_number' => "0", 'office_phone' => "4372", 'home_phone' => "0"],
            ['name' => "SHOPIA", 'position' => "Adm I.T", 'department' => "I.T SPK", 'address' => "Gedung I.T", 'employee_number' => "0", 'office_phone' => "4371", 'home_phone' => "0"],
            ['name' => "MUHAMMAD YUNUS", 'position' => "PABX Sei Pakning", 'department' => "I.T SPK", 'address' => "Gedung I.T", 'employee_number' => "0", 'office_phone' => "4100", 'home_phone' => "0"],
            ['name' => "M. HARSEN SATRIA", 'position' => "Lap. Gangguan CCTV", 'department' => "I.T SPK", 'address' => "Gedung I.T", 'employee_number' => "0", 'office_phone' => "4373", 'home_phone' => "0"],
            ['name' => "SHIFT IT", 'position' => "Operator Telp/Fac I.T", 'department' => "I.T SPK", 'address' => "Gedung I.T", 'employee_number' => "0", 'office_phone' => "4600", 'home_phone' => "0"],
            ['name' => "UPMS LAMA", 'position' => "-", 'department' => "-", 'address' => "Gedung Produksi", 'employee_number' => "0", 'office_phone' => "4150", 'home_phone' => "0"],
            ['name' => "RECEPTIONIST WISMA", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4331", 'home_phone' => "0"],
            ['name' => "DAPUR WISMA", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4332", 'home_phone' => "0"],
            ['name' => "KAMAR VIP 1", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4336", 'home_phone' => "0"],
            ['name' => "KAMAR VIP 2", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4335", 'home_phone' => "0"],
            ['name' => "KAMAR VIP 3", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4334", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 1", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4171", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 2", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4172", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 3", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4173", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 4", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4174", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 5", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4175", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 6", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4176", 'home_phone' => "0"],
            ['name' => "KAMAR STANDART 7", 'position' => "-", 'department' => "GA SPK", 'address' => "Gedung Wisma Spk", 'employee_number' => "0", 'office_phone' => "4177", 'home_phone' => "0"],
            ['name' => "MASJID AL MUKARROMAH", 'position' => "-", 'department' => "-", 'address' => "JL. Cemara", 'employee_number' => "0", 'office_phone' => "4149", 'home_phone' => "0"],
            ['name' => "GEREJA EFRATA", 'position' => "-", 'department' => "-", 'address' => "JL. Jati", 'employee_number' => "0", 'office_phone' => "4139", 'home_phone' => "0"],
            ['name' => "KANTIN PWP", 'position' => "-", 'department' => "PWP", 'address' => "Gedung Induk", 'employee_number' => "0", 'office_phone' => "4369", 'home_phone' => "0"],
            ['name' => "KOPERASI PWP", 'position' => "-", 'department' => "PWP", 'address' => "JL. Wijaya Kusuma E.06", 'employee_number' => "0", 'office_phone' => "4308", 'home_phone' => "0"],
            ['name' => "DAPUR PWP", 'position' => "-", 'department' => "PWP", 'address' => "JL. Wijaya Kusuma E.05", 'employee_number' => "0", 'office_phone' => "4681", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Ketua Harian Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Cendana", 'employee_number' => "0", 'office_phone' => "4130", 'home_phone' => "0"],
            ['name' => "NURLIA", 'position' => "Ka. TK Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Tanjung", 'employee_number' => "0", 'office_phone' => "4131", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Ka. SD Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Cendana", 'employee_number' => "0", 'office_phone' => "4132", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Keuangan Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Cendana", 'employee_number' => "0", 'office_phone' => "4133", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Ka. SLTP Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Wijaya Kusuma", 'employee_number' => "0", 'office_phone' => "4134", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Majelis Guru SLTP Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Wijaya Kusuma", 'employee_number' => "0", 'office_phone' => "4135", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "R. Majelis Guru SD", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Cendana", 'employee_number' => "0", 'office_phone' => "4330", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Ka. MDTA Yayasan", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Cemara", 'employee_number' => "0", 'office_phone' => "4138", 'home_phone' => "0"],
            ['name' => "MINI MARKET", 'position' => "-", 'department' => "YAYASAN SURIPERDANA", 'address' => "JL. Teratai", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4339"],
            ['name' => "BP. BULOPA", 'position' => "-", 'department' => "GA SPK", 'address' => "JL. Anggrek", 'employee_number' => "0", 'office_phone' => "4337", 'home_phone' => "0"],
            ['name' => "SANGGAR PRAMUKA", 'position' => "-", 'department' => "GA SPK", 'address' => "JL. Mahoni", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4511"],
            ['name' => "LAP UPACARA KTR INDUK", 'position' => "-", 'department' => "GA SPK", 'address' => "JL. Cendana", 'employee_number' => "0", 'office_phone' => "4101", 'home_phone' => "0"],
            ['name' => "BANK SAMPAH", 'position' => "-", 'department' => "PWP", 'address' => "JL. Jend. Sudirman Sejangat", 'employee_number' => "0", 'office_phone' => "4399", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "SYAHBANDAR", 'department' => "PIHAK KE III", 'address' => "JL. Melati R.11", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4604"],
            ['name' => "PT. PBAS", 'position' => "-", 'department' => "PIHAK KE III", 'address' => "JL. Rambutan D.47", 'employee_number' => "0", 'office_phone' => "4680", 'home_phone' => "0"],
            ['name' => "AHMAD MAKHRUJANI", 'position' => "Teknisi Komputer", 'department' => "I.T SPK", 'address' => "Gedung I.T", 'employee_number' => "0", 'office_phone' => "4374", 'home_phone' => "0"],
            ['name' => "KHAIRUL AMRI", 'position' => "-", 'department' => "-", 'address' => "JL. Ketapang YS.03", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4649"],
            ['name' => "POSKO CCTV", 'position' => "-", 'department' => "GA SPK", 'address' => "Area Kantor Induk", 'employee_number' => "0", 'office_phone' => "4320", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Ruang Rapat Marine", 'department' => "MARINE REG I SPK", 'address' => "Kantor Marine", 'employee_number' => "0", 'office_phone' => "4298", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Workshop IT", 'department' => "I.T SPK", 'address' => "-", 'employee_number' => "0", 'office_phone' => "4300", 'home_phone' => "0"],
            ['name' => "Tidak Ada Nama Kontak", 'position' => "Ruang Rapat Premium", 'department' => "MAN PROD SPK", 'address' => "Kantor Induk", 'employee_number' => "0", 'office_phone' => "4204", 'home_phone' => "0"],
            ['name' => "JETTY II", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Jetty 2", 'employee_number' => "0", 'office_phone' => "4217", 'home_phone' => "0"],
            ['name' => "FACHREZA ARDIAN", 'position' => "Jr Operator I Pump & Aux", 'department' => "PRODUCTION SPK", 'address' => "JL. Durian D.77", 'employee_number' => "751230", 'office_phone' => "4301", 'home_phone' => "0"],
            ['name' => "POS SEI DAYANG", 'position' => "-", 'department' => "GA SPK", 'address' => "Sei Dayang", 'employee_number' => "0", 'office_phone' => "4154", 'home_phone' => "0"],
            ['name' => "OPERATOR WATER INTAKE SEI DAYANG", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Sei Dayang", 'employee_number' => "0", 'office_phone' => "4196", 'home_phone' => "0"],
            ['name' => "MUHAMMAD IQBAL", 'position' => "JR OPR I WTP/WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "755889", 'office_phone' => "4193", 'home_phone' => "4632"],
            ['name' => "DANANG RIYANTO", 'position' => "JR OPRT I WTP.WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "755693", 'office_phone' => "4302", 'home_phone' => "4633"],
            ['name' => "MICHEAL YULINADA", 'position' => "JR OPRT I WTP.WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "755845", 'office_phone' => "4302", 'home_phone' => "4452"],
            ['name' => "MUAMMAR QADDAFI", 'position' => "JR OPR I WTP/WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "YS. 06", 'employee_number' => "755806", 'office_phone' => "4193", 'home_phone' => "4634"],
            ['name' => "GEDE FAKHRI PUTRA", 'position' => "JR OPR I WTP/WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "YS. 02", 'employee_number' => "755962", 'office_phone' => "4193", 'home_phone' => "4643"],
            ['name' => "M LUTHFI WIBOWO", 'position' => "JR OPR II JETTY", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "755910", 'office_phone' => "4302", 'home_phone' => "4646"],
            ['name' => "AL NAUFAL NAVITAMA", 'position' => "JR OPR I WTP/WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "D. 48", 'employee_number' => "755633", 'office_phone' => "4193", 'home_phone' => "4645"],
            ['name' => "WAHYU RIZALDI", 'position' => "R OPR I WTP/WDCP/WIS", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "755863", 'office_phone' => "4193", 'home_phone' => "4644"],
            ['name' => "DARYONO", 'position' => "Spv Security", 'department' => "HSSE SPK", 'address' => "Jl. Teratai R.04", 'employee_number' => "0", 'office_phone' => "4290", 'home_phone' => "4476"],
            ['name' => "TAUFIK HIDAYAT", 'position' => "-", 'department' => "HSSE SPK", 'address' => "E. 27", 'employee_number' => "0", 'office_phone' => "4322", 'home_phone' => "4541"],
            ['name' => "M. AZIZIL JABBAR", 'position' => "-", 'department' => "HSSE SPK", 'address' => "D. 13", 'employee_number' => "0", 'office_phone' => "4322", 'home_phone' => "4542"],
            ['name' => "YOGA HANAFI H", 'position' => "Jr Act I Fire Support", 'department' => "HSSE SPK", 'address' => "JL. Flamboyan E. 41", 'employee_number' => "756361", 'office_phone' => "4322", 'home_phone' => "4543"],
            ['name' => "RAHMAD DWIMA", 'position' => "-", 'department' => "HSSE SPK", 'address' => "E.14", 'employee_number' => "0", 'office_phone' => "4322", 'home_phone' => "4534"],
            ['name' => "WDCP", 'position' => "-", 'department' => "PRODUCTION SPK", 'address' => "Gedung WDCP", 'employee_number' => "0", 'office_phone' => "4316", 'home_phone' => "0"],
            ['name' => "SURANTO", 'position' => "Sr. Mech Electrical", 'department' => "MAINTENANCE SPK", 'address' => "JL. WIJAYA KUSUMA NO. 03", 'employee_number' => "753871", 'office_phone' => "4346", 'home_phone' => "4479"],
            ['name' => "R. DEMOROOM", 'position' => "-", 'department' => "HSSE SPK", 'address' => "POOL ANGKUTAN", 'employee_number' => "0", 'office_phone' => "4383", 'home_phone' => "0"],
            ['name' => "ARYA ANINDA W", 'position' => "Jr ENG II OFFIISTE FAC PROCESS", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "755064", 'office_phone' => "4396", 'home_phone' => "0"],
            ['name' => "BUDI DARMAWAN", 'position' => "SHIFT SPV CDU", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "728306", 'office_phone' => "4313", 'home_phone' => "0"],
            ['name' => "REVIN NAZIF AL", 'position' => "JR OPRT I HEATER/TOWER", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "756342", 'office_phone' => "4315", 'home_phone' => "4521"],
            ['name' => "MHD HANAFI", 'position' => "LOAD MASTER I SPK", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "747042", 'office_phone' => "4314", 'home_phone' => "0"],
            ['name' => "MUHAMMAD HAIKAL", 'position' => "JR OPRT I IPAL & SEPERATOR", 'department' => "PRODUCTION SPK", 'address' => "-", 'employee_number' => "756346", 'office_phone' => "4304", 'home_phone' => "0"],
            ['name' => "MUHAMMAD IVALDY", 'position' => "Jr. Technician I Electrical & Instrument", 'department' => "MAINTENANCE SPK", 'address' => "JL. Flamboyan E. 23", 'employee_number' => "756379", 'office_phone' => "4364", 'home_phone' => "0"],
            ['name' => "IKSAN ABDULLAH", 'position' => "Sr. Supervisor Maintenance", 'department' => "MAINTENANCE SPK", 'address' => "-", 'employee_number' => "727967", 'office_phone' => "4363", 'home_phone' => "0"],
            ['name' => "RIZKI VAITA PUTRA", 'position' => "Jr. Technician NRE & Civil", 'department' => "MAINTENANCE SPK", 'address' => "-", 'employee_number' => "756373", 'office_phone' => "4258", 'home_phone' => "0"],
            ['name' => "WILLIAM HARTANTO", 'position' => "Sr Technician I Mechanical & Civil", 'department' => "MAINTENANCE SPK", 'address' => "-", 'employee_number' => "755610", 'office_phone' => "4350", 'home_phone' => "0"],
            ['name' => "ARIEF MUHAMMAD HAEKAL", 'position' => "Jr. Analyst I Planning NRE & Civil", 'department' => "MAINTENANCE SPK", 'address' => "-", 'employee_number' => "746087", 'office_phone' => "4352", 'home_phone' => "0"],
            ['name' => "IYAN CAHYADI F", 'position' => "Jr Ast I Fire Support Spk", 'department' => "HSSE SPK", 'address' => "JL. Melati D.15", 'employee_number' => "756369", 'office_phone' => "4322", 'home_phone' => "4576"],
            ['name' => "KANTOR PWP", 'position' => "PWP", 'department' => "PWP", 'address' => "PATRA MART", 'employee_number' => "0", 'office_phone' => "4683", 'home_phone' => "0"],
            ['name' => "ADSL KOPERASI PWP", 'position' => "-", 'department' => "PWP", 'address' => "KOPERASI PWP", 'employee_number' => "0", 'office_phone' => "4684", 'home_phone' => "0"],
            ['name' => "SOULI", 'position' => "-", 'department' => "HSSE SPK", 'address' => "E.44", 'employee_number' => "0", 'office_phone' => "4322", 'home_phone' => "4428"],
            ['name' => "TIM PROPER SPK", 'position' => "-", 'department' => "GA SPK", 'address' => "KANTOR INDUK", 'employee_number' => "0", 'office_phone' => "4360", 'home_phone' => "0"],
            ['name' => "TIM PROPER SPK", 'position' => "-", 'department' => "GA SPK", 'address' => "KANTOR INDUK", 'employee_number' => "0", 'office_phone' => "4360", 'home_phone' => "0"],
            ['name' => "EKO SAPUTRO", 'position' => "-", 'department' => "PROCUREMENT SPK", 'address' => "JL. SEDAP MALAM D. 06", 'employee_number' => "0", 'office_phone' => "0", 'home_phone' => "4597"],
            ['name' => "ILHAM SULAIMAN", 'position' => "BKO SECURITY", 'department' => "HSSE SPK", 'address' => "D. 41", 'employee_number' => "0", 'office_phone' => "4291", 'home_phone' => "4594"]
        ];

        foreach ($data as $item) {
            Telephone::create($item);
        }
    }
}
